### ISSUE TITLE
Focus outlines of links are a bit misaligned

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/contextual-help#19]
Hi ,

As shown in the following images, the outlines of the links when they are focused, are a bit misaligned. Would be nicer if there was a small padding around.

![image](https://cloud.githubusercontent.com/assets/10680296/25426936/8814f0a8-2a8e-11e7-8afb-f4d82974d303.png)

![image](https://cloud.githubusercontent.com/assets/10680296/25426969/a109d3c6-2a8e-11e7-808a-3247f68441ac.png)

Regards,
@dinukadesilva

**Comment by StommePoes** [comment]
Agreed, this will be taken care of when we get contextual-help up to the current design (it's actually not quite the same as the latest-design seen on the UX Framework site). DES-632 in our Jira

**Comment by wyseguyonline** [comment]
I have added a link to this issue under 'acceptance criteria' on the aforementioned Jira story.

**Comment by StommePoes** [comment]
This should have been fixed a while back. A new pull should show the issue fixed.
