### ISSUE TITLE
Main entry has not been specified in the package.json

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/contextual-help#20]
`contextual-help` module cannot be used as follows since the main entry of package.json has not been specified.

```
var ContextualHelp = require('@pearson-components/contextual-help');
ContextualHelp.init();
```

Regards,
@dinukadesilva

**Comment by StommePoes** [comment]
This is how Console uses it:
In https://bitbucket.pearson.com/projects/OCC/repos/console-ui/browse/src/app.js
```
import '@pearson-components/app-header/build/dist.app-header';
import '@pearson-components/contextual-help/build/dist.contextual-help';
```
in https://bitbucket.pearson.com/projects/OCC/repos/console-ui/browse/src/utils/setHeaderSession.js
```
const setLoggedOutSession = (element) => {
...
  document.dispatchEvent(new CustomEvent('o.InitContextualHelp'));
};
```

**Comment by dinukadesilva** [comment]
This is exactly correct @StommePoes and I had done the same way for now. And it works perfect. 

Please find the pull request I have sent with the required change.
#22
