### ISSUE TITLE
Some modules are imported with inline loaders

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/contextual-help#24]
I would say that we should try to avoid inline loaders since that reduces the control given to webpack config.

![image](https://user-images.githubusercontent.com/10680296/27582630-353f332e-5b4f-11e7-8190-85aa64bda6fb.png)

https://github.com/Pearson-Higher-Ed/contextual-help/blob/master/src/js/ContextualHelp.js#L6

**Comment by wyseguyonline** [comment]
Looking into this and testing your PR.
