### ISSUE TITLE
Spacing issues around paragraphs

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/contextual-help#29]
Pam Mayne with the UA team has brought up some spacing issues with the contextual help component. Mostly it looks like all paragraphs have a 25px spacing, when it should just inherit the standard 12px from the typography component.

<img width="296" alt="screen shot 2017-11-17 at 11 53 46 am" src="https://user-images.githubusercontent.com/13319923/32963750-34864abc-cb8e-11e7-9527-889e86adc7f3.png">
<img width="316" alt="screen shot 2017-11-17 at 11 53 35 am" src="https://user-images.githubusercontent.com/13319923/32963763-3b95d638-cb8e-11e7-946f-de7ea9a05d8e.png">

Looking at the design docs it seems that the redlines were updates and are now kind of ambiguous on this, I will add a story to get those updated as well.

**Comment by JasonLantz** [comment]
Closing this issue. This component has been refactored.
